#!/bin/bash

supp_dir="$HOME/.bash_extras"
supp_files=(exports functions aliases completions secrets local_settings)

load_extras() {
    if [[ -z "$1" ]]; then
        echo "cannot source nothing, something went wrong in bashrc"
    else
        for supp_file in "$supp_dir/$1"*; do
            # shellcheck disable=SC1090
            [[ -f $supp_file ]] && source "$supp_file"
        done
    fi
}

update_path() {
    # only updates PATH if directory is not already there
    local new_path
    for new_path in "$@"; do
        case ":$PATH:" in
            # check glob match for new_path in the current PATH
            *:"$new_path":*) ;;
            *)
                export PATH="$new_path:$PATH"
                ;;
        esac
    done
}

shopt -s cdspell
shopt -s checkwinsize
shopt -s dirspell
shopt -s expand_aliases
shopt -s globstar
shopt -s histappend
shopt -s no_empty_cmd_completion
# shopt -s nullglob

# load exports first
load_extras "${supp_files[0]}"

# load the rest
for supp_type in "${supp_files[@]:1}"; do
    load_extras "$supp_type"
done

if [[ $(uname -s) == "Darwin" ]]; then
    check_macos_hostname
fi

# shellcheck disable=SC1091
[[ -f $HOME/liquidprompt/liquidprompt && $- = *i* ]] && source "$HOME/liquidprompt/liquidprompt"

# remap caps lock to compose
if command -v setxkbmap &>/dev/null; then
    setxkbmap -option compose:caps
fi
