# shellcheck shell=bash
supp_dir="$HOME/.bash_extras"
supp_files=(exports functions aliases completions secrets local_settings)

load_extras() {
    if [[ -z "$1" ]]; then
        echo "cannot source nothing, something went wrong in bashrc"
    else
        for supp_file in "$supp_dir/$1"*; do
            # shellcheck source=/dev/null
            [[ -f $supp_file ]] && source "$supp_file"
        done
    fi
}

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s globstar

# load exports first
load_extras "${supp_files[0]}"

# set up conda, if present
if [[ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
    conda activate "${DEFAULT_CONDA_ENV:-base}"
fi

# load the rest
for supp_type in "${supp_files[@]:1}"; do
    load_extras "$supp_type"
done

# stupid default umask
umask 002

# shellcheck source=/dev/null
[[ -f $HOME/liquidprompt/liquidprompt ]] && [[ $- = *i* ]] && source "$HOME/liquidprompt/liquidprompt"
