#!/bin/bash

HERE=$(dirname "$(resolve_path "${BASH_SOURCE[0]}")")

# custom completions
if [[ -d /etc/bash_completion.d/ ]]; then
    for file in /etc/bash_completion.d/*; do
        # shellcheck source=/dev/null
        [[ -f $file ]] && source "$file"
    done
fi

declare -A comp
comp[doctl]="doctl completion bash"
comp[pip]="pip completion --bash"
# shellcheck disable=2089
comp[aws]="echo complete -C aws_completer aws"

# pip and doctl
for comp_name in ${!comp[*]}; do
    # shellcheck disable=2065
    test which "$comp_name" >/dev/null 2>&1 || continue

    comp_file="$HERE/completions_${comp_name}"
    if [[ ! -e "$comp_file" ]]; then
        ${comp[$comp_name]} >"$comp_file"
    fi
    # shellcheck source=/dev/null
    source "$comp_file"
done
