#!/bin/bash

HERE=$(dirname "$(resolve_path "${BASH_SOURCE[0]}")")

# things I don't need / or aren't working nicely
IGNORE_COMPLETIONS=" fcoeadm fcoemon lldptool lldpad "
if [[ -d /etc/bash_completion.d/ ]]; then
    for file in /etc/bash_completion.d/lldptool /etc/bash_completion.d/* /etc/bash_completion.d/fcoeadm; do
        if [[ "${IGNORE_COMPLETIONS/ $(basename "$file") /}" != "$IGNORE_COMPLETIONS" ]]; then
            continue
        fi
        # shellcheck source=/dev/null
        [[ -f $file ]] && source "$file"
    done
fi

declare -A comp check
comp[doctl]="doctl completion bash"
comp[pip]="pip completion --bash"
# shellcheck disable=2089
comp[aws]="echo complete -C aws_completer aws"

# pip and doctl
for comp_name in ${!comp[*]}; do
    if [[ -n ${check["$comp_name"]} ]]; then
        cmd_check="${check[$comp_name]}"
    else
        cmd_check=(which "$comp_name")
    fi
    test "${cmd_check[@]}" >&/dev/null 2>&1 || continue

    comp_file="$HERE/completions_${comp_name}"
    if [[ ! -e "$comp_file" ]]; then
        ${comp[$comp_name]} >"$comp_file"
    fi
    # shellcheck source=/dev/null
    source "$comp_file"
done
